# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f3f4518e91dff9f6b749fc4bfdef545149d5534829de411d44064e5d83ea96225edf917dc8fd26e79d53904f90c42ee894c40c0acb16bd5692406c9e09136547

test:
  secret_key_base: e6316c32f960252e135b70a5181a5aed8b6783e2746f5b6d7c885ad896fcbc2aa61aabdc795795ed491577a1b651c7451750928e868c38156fcf175cbeff26ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
